PropertyNinja/Controllers/BuyerListingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PropertyNinja.Data;
using PropertyNinja.Models;
using X.PagedList.Mvc.Core;
using X.PagedList;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;
using Microsoft.Extensions.Configuration;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace PropertyNinja.Controllers
{
    public class BuyerListingController : Controller
    {
        private readonly PropertyNinjaContext _context;

        public BuyerListingController(PropertyNinjaContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string searchString, string sortBy, int? page)
        {
            var properties = from m in _context.Property
                             select m;

            ViewBag.Count = properties.Count();

            //Search based on input if searchString not empty.
            if (!String.IsNullOrEmpty(searchString))
            {
                properties = properties.Where(s => s.PropertyType.Contains(searchString) 
                                                || s.PropertyName.Contains(searchString) 
                                                || s.PropertyAddress.Contains(searchString)
                                                 || s.PropertyPrice.ToString().Contains(searchString)
                                                || searchString == null);
                
                ViewBag.Count = properties.Count();
            }
            else
            {
                //Runs sorting if searchString empty and search button is clicked
                if (sortBy == "priceLow")
                {
                    properties = from s in _context.Property
                                 orderby s.PropertyPrice ascending
                                 select s;
                }
                else if (sortBy == "priceHigh")
                {
                    properties = from s in _context.Property
                                 orderby s.PropertyPrice descending
                                 select s;
                }
                else if (sortBy == "landLow")
                {
                    properties = from s in _context.Property
                                 orderby s.PropertyLandSize ascending
                                 select s;
                }
                else if (sortBy == "landHigh")
                {
                    properties = from s in _context.Property
                                 orderby s.PropertyLandSize descending
                                 select s;
                }
                else if (sortBy == "bedroomLow")
                {
                    properties = from s in _context.Property
                                 orderby s.PropertyBedroom ascending
                                 select s;
                }
                else if (sortBy == "bedroomHigh")
                {
                    properties = from s in _context.Property
                                 orderby s.PropertyBedroom descending
                                 select s;
                }
            }

            //Returns the properties in a paged list
            return View(properties.ToList().ToPagedList(page ?? 1, 6));
        }

        [Authorize]
        public async Task<IActionResult> PropertyDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property
                .FirstOrDefaultAsync(m => m.ID == id);

            if (@property == null)
            {
                return NotFound();
            }

            ViewBag.images = GetBlobs(@property.PropertyName.ToLower().Replace(",", "").Replace(" ", "-"));


            return View(@property);
        }

        //GET Blob storage info
        private CloudBlobClient getBlobStorageInformation()
        {
            //read json
            var builder = new ConfigurationBuilder()
                            .SetBasePath(Directory.GetCurrentDirectory())
                            .AddJsonFile("appsettings.json");
            IConfigurationRoot configure = builder.Build();

            //to get key access
            //once link, time to read the content to get the connectionstring
            CloudStorageAccount objectaccount = CloudStorageAccount.Parse(configure["Connectionstrings:storageconnection"]);

            CloudBlobClient blobclientagent = objectaccount.CreateCloudBlobClient();

            return blobclientagent;
        }

        //Function to get blobs based on the property name
        public List<string> GetBlobs(string name)
        {
            try
            {
                CloudBlobClient client = getBlobStorageInformation();

                //Creates a container using property name entered by seller
                CloudBlobContainer container = client.GetContainerReference(name);

                //create empty list to store for the blobs list information
                List<string> blobs = new List<string>();

                //get the listing record from the blob storage
                BlobResultSegment result = container.ListBlobsSegmentedAsync(null).Result;

                //read blob listing from the storage
                foreach (IListBlobItem item in result.Results)
                {
                    //check thge type of blob : block blob or directory or page block
                    if (item.GetType() == typeof(CloudBlockBlob))
                    {
                        CloudBlockBlob blob = (CloudBlockBlob)item;
                        blobs.Add(blob.Name + "#" + blob.Uri.ToString());
                    }
                    else if (item.GetType() == typeof(CloudBlobDirectory))
                    {
                        CloudBlobDirectory blob = (CloudBlobDirectory)item;
                        blobs.Add(blob.Uri.ToString());
                    }
                }

                return blobs;

            }
            catch (Exception ex)
            {

                throw;
            }
        }

        //To view seller details (might need to move to other user related controller)
        public async Task<IActionResult> ViewSeller(string sellerName, int? page)
        {
            ViewBag.sellerName = sellerName;

            var properties = from m in _context.Property
                             select m;
            
            if (!String.IsNullOrEmpty(sellerName))
            {
                properties = properties.Where(s => s.PropertyType.Equals(sellerName));

                ViewBag.Count = properties.Count();
            }

            return View(properties.ToList().ToPagedList(page ?? 1, 3));
        }
    }
}

PropertyNinja/Controllers/PropertiesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PropertyNinja.Data;
using PropertyNinja.Models;
using Microsoft.Azure.Storage;
using Microsoft.Azure.Storage.Blob;
using Microsoft.Extensions.Configuration;
using PropertyNinja.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using PropertyNinja.Controllers;
using Microsoft.Azure.ServiceBus;
using System.Text;
using Microsoft.AspNetCore.Authorization;

namespace PropertyNinja.Views.Properties
{
    [Authorize]
    public class PropertiesController : Controller
    {
        private readonly PropertyNinjaContext _context;
        private readonly UserManager<PropertyNinjaUser> _userManager;

        public PropertiesController(PropertyNinjaContext context, UserManager<PropertyNinjaUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        //GET Blob storage info
        public CloudBlobClient getBlobStorageInformation()
        {
            //read json
            var builder = new ConfigurationBuilder()
                            .SetBasePath(Directory.GetCurrentDirectory())
                            .AddJsonFile("appsettings.json");
            IConfigurationRoot configure = builder.Build();

            //to get key access
            //once link, time to read the content to get the connectionstring
            CloudStorageAccount objectaccount = CloudStorageAccount.Parse(configure["Connectionstrings:storageconnection"]);

            CloudBlobClient blobclientagent = objectaccount.CreateCloudBlobClient();

            return blobclientagent;
        }

        // GET: Properties
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var properties = from m in _context.Property
                             select m;

            if (user != null)
            {
                var name = user.Name;
                properties = properties.Where(s => s.PropertyType.Equals(name));
            }

            return View(await properties.ToListAsync());
        }

        // GET: Properties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // GET: Properties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Properties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(List<IFormFile> files, [Bind("ID,PropertyType,PropertyName,PropertyAddress,PropertyBedroom,PropertyBathroom,PropertyFurnishing,PropertyDescription,PropertyLandSize,PropertySeller,PropertyPostedDate,PropertyPrice")] Property @property)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    CloudBlobClient client = getBlobStorageInformation();

                    //Creates a container using property name entered by seller
                    CloudBlobContainer container = client.GetContainerReference(@property.PropertyName.ToLower().Replace(",", "").Replace(" ", "-"));

                    container.CreateIfNotExists();

                    //Sends the blob parallely from the file list uploaded
                    Parallel.ForEach(files, file =>
                    {
                        string[] permittedExtensions = { ".jpg", ".jpeg", ".png" };

                        var ext = Path.GetExtension(file.FileName).ToLowerInvariant();

                        // To check file extension
                        if (string.IsNullOrEmpty(ext) || !permittedExtensions.Contains(ext))
                        {
                            // If extension is invalid
                            ViewBag.fileError = true;
                        }
                        else
                        {
                            //Blob name will be the file name
                            CloudBlockBlob blob = container.GetBlockBlobReference(file.FileName);

                            blob.UploadFromStreamAsync(file.OpenReadStream());
                        }
                    });
                }
                catch (Exception ex)
                {
                    throw;
                }

                if (ViewBag.fileError != true)
                {
                    //TO STORE THE THUMBNAIL IMAGE FOR PROPERTIES LISTING
                    @property.PropertyThumbnail = files.First().FileName;
                    @property.PropertyPostedDate = DateTime.Now;

                    //Send a service bus message
                    ServiceBusController.queueClient = new QueueClient(ServiceBusController.ServiceBusConnectionString, ServiceBusController.QueueName);
                    var qmessage = new Message(Encoding.UTF8.GetBytes(@property.PropertyName));
                    await ServiceBusController.queueClient.SendAsync(qmessage);

                    _context.Add(@property);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(@property);
        }

        // GET: Properties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property.FindAsync(id);
            if (@property == null)
            {
                return NotFound();
            }
            return View(@property);
        }

        // POST: Properties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,PropertyType,PropertyName,PropertyAddress,PropertyBedroom,PropertyBathroom,PropertyFurnishing,PropertyDescription,PropertyLandSize,PropertySeller,PropertyPostedDate")] Property @property)
        {
            if (id != @property.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@property);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PropertyExists(@property.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@property);
        }

        // GET: Properties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @property = await _context.Property
                .FirstOrDefaultAsync(m => m.ID == id);
            if (@property == null)
            {
                return NotFound();
            }

            return View(@property);
        }

        // POST: Properties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @property = await _context.Property.FindAsync(id);
            _context.Property.Remove(@property);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PropertyExists(int id)
        {
            return _context.Property.Any(e => e.ID == id);
        }
    }
}

PropertyNinja/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using PropertyNinja.Areas.Identity.Data
@inject SignInManager<PropertyNinjaUser> SignInManager
@inject UserManager<PropertyNinjaUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);
}﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PropertyNinja</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-red.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/d2d336674d.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">PropertyNinja</span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    @if (SignInManager.IsSignedIn(User) && user.Role == "seller")
                    {
                        <a class="mdl-navigation__link" asp-area="" asp-controller="Properties" asp-action="Index">Manage Properties</a>
                        <a class="mdl-navigation__link" asp-area="" asp-controller="Enquiry" asp-action="GetEnquiries" asp-route-sellerName="@user.Name">Manage Enquiries</a>
                    }
                    else
                    {
                        <a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="mdl-navigation__link" asp-area="" asp-controller="BuyerListing" asp-action="Index">Properties</a>
                    }
                    <partial name="_LoginPartial" />
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Title</span>
            <nav class="mdl-navigation">
                @if (SignInManager.IsSignedIn(User) && user.Role == "seller")
                {
                    <a class="mdl-navigation__link" asp-area="" asp-controller="BuyerListing" asp-action="Index">Manage Properties</a>
                    <a class="mdl-navigation__link" asp-area="" asp-controller="Enquiry" asp-action="GetEnquiries" asp-route-sellerName="@user.Name">Manage Enquiries</a>
                }
                else
                {
                    <a class="mdl-navigation__link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="mdl-navigation__link" asp-area="" asp-controller="BuyerListing" asp-action="Index">Properties</a>
                }
                <partial name="_LoginPartial" />
            </nav>
        </div>
        <main class="mdl-layout__content">
            <div class="page-content">
                @RenderBody()
            </div>
            <div class="mdl-mini-footer">
                <div class="mdl-mini-footer__left-section">
                    <div class="mdl-logo">PropertNinja</div>
                    <ul class="mdl-mini-footer__link-list">
                        @if (SignInManager.IsSignedIn(User) && user.Role == "seller")
                        {
                            <a class="mdl-navigation__link" asp-area="" asp-controller="BuyerListing" asp-action="Index">Manage Properties</a>
                            <a class="mdl-navigation__link" asp-area="" asp-controller="Enquiry" asp-action="GetEnquiries" asp-route-sellerName="@user.Name">Manage Enquiries</a>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                            <li><a asp-area="" asp-controller="BuyerListing" asp-action="Index">Properties</a></li>
                        }
                    </ul>
                </div>
            </div>
        </main>
    </div>

    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Styles", required: false)
    @RenderSection("Scripts", required: false)
</body>
</html>